source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'demoPod_Example', :exclusive => true do
  pod "demoPod", :path => "../"
end

target 'demoPod_Tests', :exclusive => true do
  pod "demoPod", :path => "../"

  
end
